spec: fix bare words error with ProcDump 1.3 for el9 (#150)
RPM 4.16 removed support for bare words in expressions (eg a == b needs to be a == b now).
The change is backward compatible. More changes are in: https://rpm.org/wiki/Releases/4.16.0

This patch accommodates the above change and fixes more errors/warnings:
error: bare words are no longer supported, please use ...: redhat == debbuild
error: ^
error: /root/ProcDump-for-Linux/pkgbuild/SPECS/procdump.spec:6: bad %if condition: redhat == debbuild
make: *** [Makefile:91: rpm] Error 1